# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 00:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20170622_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
